# YOLO detection settings.
detection:
  model_path: 'ckpt/best_yolo.pt'
  confidence_threshold: 0.5

# Display settings.
display:
  window_name: "YOLO OBB Detection"

# Camera-to-end-effector hand-eye calibration matrix.
camera_extrinsics:
  matrix:
    - [9.98312756e-01, 5.35906216e-02, -2.23536524e-02, 4.85322248e-03]
    - [-4.50777375e-02, 9.57941852e-01, 2.83399727e-01, -7.08128813e-02]
    - [3.66010667e-02, -2.81913911e-01, 9.58741315e-01, 4.37687644e-02]
    - [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]

# RealSense stream settings.
camera_streams:
  color:
    width: 640
    height: 480
    format: 'bgr8'
    fps: 30
  depth:
    width: 640
    height: 480
    format: 'z16'
    fps: 30

# Depth post-processing settings.
depth_processing:
  kernel_size: 5
